services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - /home/manualva/data/mariadb:/var/lib/mysql
    restart: always
    networks:
      - manualvanet
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/manualva/data/wordpress:/var/www/html
    restart: always
    env_file:
      - .env
    networks:
      - manualvanet
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    volumes:
      - /home/manualva/data/wordpress:/var/www/html
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    networks:
      - manualvanet

networks:
  manualvanet:
    name: manualvanet
    driver: bridge

secrets:
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt