services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    volumes:
      - /home/manualva/data/mariadb:/var/lib/mysql
    restart: always
    networks:
      - manualvanet
    env_file:
      - .env

networks:
  manualvanet:
    name: manualvanet
    driver: bridge